#!/bin/bash
isModLoadingPhase=false
. /home/minecraft/watchdog.cfg

packidAppend=$(echo $packid)
packidString="Server"
packid=$packidAppend$packidString
export packid=$packid
export packidString=$packidString
export packidAppend=$packidAppend

export msgAppend='Going down for scheduled restart NOW!'; . /home/minecraft/watchdog -i
. /home/minecraft/'$packid'/'$packidAppend' stop
. /home/minecraft/watchdog -ul

